### ISSUE TITLE
Not REST route API

### ISSUE THREAD

**Issue by shafhik** [ordent/ramenbox#3]
![image](https://user-images.githubusercontent.com/14273364/92368219-a43e9100-f121-11ea-86c3-338225997ed3.png)

on the list there are route /create and /edit with GET , i'm sure it should be POST
the create and edit method isn't available in the controller either

**Comment by ddg00** [comment]
please refer to this official documentation
https://adonisjs.com/docs/4.1/routing#_route_resources
