### ISSUE TITLE
putItem update related slug Failed occasionally

### ISSUE THREAD

**Issue by shafhik** [ordent/ramenbox#5]
when i tried to update some of the data using slug source 
ex : i set name as slug filed source, when i update the name sometime it failed, but after i wait a bit and tried again, it works. and if i try to update it immediately it failed again. I'm not quite sure either why this is happened

note : it works fine with other field not related to slug

**Comment by ddg00** [comment]
this issue may reffer to [Adonis Lucid Slugify](https://www.npmjs.com/package/@adonisjs/lucid-slugify#options) option set `"disableUpdates" = false`
