### ISSUE TITLE
File Services have a problem

### ISSUE THREAD

**Issue by shafhik** [ordent/ramenbox#7]
Every time i tried to put json data type it always return 

{
  "data": null,
  "meta": {
    "message": "File Services have a problem",
    "status": 500,
    "code": "E_ERROR",
    "stack": []
  }
}

I guess it assume my body input as a file, and it's error because the driver not set up properly, and it's kinda make ramen-box with ramen adonis-driver dependent on each other

**Comment by shafhik** [comment]
on file service there is checking variable type using
if (typeof item === "object") {

it should be 
if (typeof item === 'object' && item.constructor.name === 'File') {
to by pass object variable excluding file

**Comment by ddg00** [comment]
fixed at version 2.1.37
https://github.com/ordent/ramenbox/commit/2f94359355be2f5c3292c20c55ed390f0d5cb64f
