### ISSUE TITLE
Floppy Error

### ISSUE THREAD

**Issue by shafhik** [ordent/ramenbox#8]
Error Floppy when storing data.

i solve this by install those package : 
-  "floppy": "^1.0.0",
- "@slynova/flydrive": "^1.0.3",

also try install "@adonisjs/drive": "^1.0.4", and dont forget register it on start/app

**Comment by ddg00** [comment]
fixed at version [2.1.38](https://github.com/ordent/ramenbox/releases/tag/2.1.38)
